import { erc20ABI } from './erc20ABI';
import { gaugeControllerABI, gaugeControllerV2ABI } from './gaugeControllerABI';
import { votingEscrowABI } from './votingEscrowABI';
import { mirroredVotingEscrowABI } from './mirroredVotingEscrowABI';
import { gaugeABI } from './gaugeABI';
import { baamABI } from './BAAM';
import { layerZeroEndpointAbi } from './layerZeroEndpoint';
import { layerZeroMirrorGateAbi } from './layerZeroMirrorGate';
import { multiChainMirrorGateAbi } from './multiChainMirrorGate';
import { multiChainMirrorGateV2Abi } from './multiChainMirrorGateV2';
import { multiChainMirrorGateV3Abi } from './multiChainMirrorGateV3';

export const ERC20_ABI = erc20ABI;
export const VOTING_ESCROW_ABI = votingEscrowABI;
export const GAUGE_CONTROLLER_ABI = gaugeControllerABI;
export const GAUGE_CONTROLLER_V2_ABI = gaugeControllerV2ABI;
export const GAUGE_ABI = gaugeABI;
export const BAAM_ABI = baamABI;
export const LAYER_ZERO_ENDPOINT_ABI = layerZeroEndpointAbi;
export const LAYER_ZERO_MIRROR_GATE_ABI = layerZeroMirrorGateAbi;
export const MULTICHAIN_MIRROR_GATE_ABI = multiChainMirrorGateAbi;
export const MULTICHAIN_MIRROR_GATE_V2_ABI = multiChainMirrorGateV2Abi;
export const MULTICHAIN_MIRROR_GATE_V3_ABI = multiChainMirrorGateV3Abi;
export const MIRRORED_VOTING_ESCROW_ABI = mirroredVotingEscrowABI;
